[project]
name = "STAR"
version = "0.1.0"
description = "STAR: Scoped Test-time Adaptation and Refinement for Neural Routing Solvers"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "numpy",
    "pybind11",
    "cython",
    "vrplib",
    "torch",
    "torchvision",
    "tqdm",
    "entmax",
    "scipy",
    "pandas",
    "jax>=0.4.13",
    "torch-cluster",
    "tensorboard-logger",
    "pytz",
    "matplotlib",
    "pyyaml",
    "tensorflow",
    "torch_geometric",
    "flax",
    "torch_cluster",
    "pytorch_lightning",
    "jaxlib",
    "numba",
    "scikit-learn",
    "seaborn"
]

[build-system]
requires = ["setuptools>=45", "wheel", "cython", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.uv.extra-build-dependencies]
torch-cluster = ["torch"]
